### ISSUE TITLE
Debian 9 and CentOS 7 error when first time install

### ISSUE THREAD

**Issue by ckc** [intercity/intercity#29]
Do you want to run Intercity on a custom port?
This allows you to run both the Intercity control panel and deploy your apps on this server.
Intercity will then be reachable on tyo-main.jp.***.hk:8843.

Ambiguous choice.  Please choose one of [1, 2, yes, no].
?  1
---- Installing docker
2018-04-07 02:55:47 URL:https://get.docker.com/ [13556/13556] -> "-" [1]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch edge" > /etc/apt/sources.list.d/docker.list
+ [ debian = debian ]
+ [ stretch = wheezy ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
---- Downloading Intercity
/var/intercity-cli/lib/app/lib/intercity_server/installer.rb:85:in ``': No such file or directory - git (Errno::ENOENT)
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:85:in `clone_intercity'
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:48:in `execute'
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:9:in `execute'
	from /var/intercity-cli/lib/app/intercity-server.rb:38:in `install'
	from /var/intercity-cli/lib/app/intercity-server.rb:11:in `start'
	from /var/intercity-cli/lib/app/intercity-server.rb:66:in `<main>'

**Comment by ckc** [comment]
CenOS 7.4

May I know what distributed suitable for Intercity?
Thx  

---- Installing docker
2018-04-07 03:29:39 URL:https://get.docker.com/ [13790/13790] -> "-" [1]
+ sh -c 'yum install -y -q yum-utils'
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
+ '[' edge '!=' stable ']'
+ sh -c 'yum-config-manager --enable docker-ce-edge'
+ sh -c 'yum makecache'

+ sh -c 'yum install -y -q docker-ce'
warning: /var/cache/yum/x86_64/7/docker-ce-edge/packages/docker-ce-18.03.0.ce-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060a 61c5 1b55 8a7f 742b 77aa c52f eb6b 621e 9f35
 From       : https://download.docker.com/linux/centos/gpg
---- Downloading Intercity
/var/intercity-cli/lib/app/lib/intercity_server/installer.rb:85:in ``': No such file or directory - git (Errno::ENOENT)
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:85:in `clone_intercity'
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:48:in `execute'
	from /var/intercity-cli/lib/app/lib/intercity_server/installer.rb:9:in `execute'
	from /var/intercity-cli/lib/app/intercity-server.rb:38:in `install'
	from /var/intercity-cli/lib/app/intercity-server.rb:11:in `start'
	from /var/intercity-cli/lib/app/intercity-server.rb:66:in `<main>'

**Comment by ckc** [comment]
I checked github install doc found that ubuntu required.
Thx
